"""Execute tavily search queries for M-check or U-check (v1.5 time-bounded).

Reads <working_dir>/queries.json (generated by `scripts/build_queries.py`), runs all M-check or U-check
queries, writes <working_dir>/tavily_<check>_results.json with snippets + URLs.

v1.5 anti-leakage barrier: Tavily searches are time-bounded to a window that
predates the candidate's founding date, so historical-candidate evaluation
doesn't see post-founding outcome news. The orchestrator must pass either:
  - explicit --start-date / --end-date (ISO YYYY-MM-DD), OR
  - --founding-year YYYY, in which case the window is computed as
    [{Y-3}-01-01, {Y}-12-31]

Tavily limits: 1000 req/mo, 1 RPS. Sleep 1.5s between calls.
Set the API key through the TAVILY_API_KEY environment variable.

Usage:
  python3 run_tavily.py --working-dir <path> --check {m|u} --founding-year 2017
  python3 run_tavily.py --working-dir <path> --check {m|u} \\
      --start-date 2014-01-01 --end-date 2017-12-31

Optional:
  --max-results N     (default 4)
  --sleep S           (default 1.5)
  --queries-file P    (default <working_dir>/queries.json)
"""

import argparse
import json
import os
import re
import sys
import time
from datetime import datetime
from pathlib import Path

ISO_DATE_RE = re.compile(r"^\d{4}-\d{2}-\d{2}$")


def load_api_key() -> str:
    key = os.environ.get("TAVILY_API_KEY")
    if key:
        return key
    sys.exit("ERROR: TAVILY_API_KEY is not set.")


def resolve_window(args) -> tuple:
    """Resolve --start-date / --end-date or compute from --founding-year.

    Returns (start_date, end_date) as ISO YYYY-MM-DD strings, or (None, None)
    if no window specified (caller should refuse to proceed in v1.5).
    """
    if args.start_date and args.end_date:
        for label, val in [("start-date", args.start_date), ("end-date", args.end_date)]:
            if not ISO_DATE_RE.match(val):
                sys.exit(f"ERROR: --{label}={val!r} not ISO YYYY-MM-DD")
        return args.start_date, args.end_date

    if args.founding_year is not None:
        year = args.founding_year
        if year < 1900 or year > 2099:
            sys.exit(f"ERROR: --founding-year={year} outside [1900, 2099]")
        return f"{year - 3}-01-01", f"{year}-12-31"

    return None, None


def main():
    parser = argparse.ArgumentParser(description="Execute tavily queries for M/U-check (v1.5)")
    parser.add_argument("--working-dir", required=True)
    parser.add_argument("--check", choices=["m", "u"], required=True)
    parser.add_argument("--max-results", type=int, default=4)
    parser.add_argument("--sleep", type=float, default=1.5)
    parser.add_argument("--queries-file")
    parser.add_argument(
        "--founding-year", type=int,
        help="Candidate founding year. Auto-computes window [Y-3-01-01, Y-12-31].",
    )
    parser.add_argument(
        "--start-date",
        help="ISO YYYY-MM-DD. Overrides --founding-year if both given.",
    )
    parser.add_argument(
        "--end-date",
        help="ISO YYYY-MM-DD. Overrides --founding-year if both given.",
    )
    args = parser.parse_args()

    try:
        from tavily import TavilyClient
    except ImportError:
        sys.exit(
            "ERROR: tavily-python not installed. Install with: pip install tavily-python --break-system-packages"
        )

    start_date, end_date = resolve_window(args)
    if not start_date or not end_date:
        sys.exit(
            "ERROR: time-bounded retrieval window required in v1.5. "
            "Pass --founding-year YYYY (auto-computes [Y-3-01-01, Y-12-31]) "
            "or --start-date YYYY-MM-DD --end-date YYYY-MM-DD."
        )

    working_dir = Path(args.working_dir).resolve()
    queries_path = Path(args.queries_file) if args.queries_file else working_dir / "queries.json"
    if not queries_path.exists():
        sys.exit(f"ERROR: queries file not found: {queries_path}")

    queries_data = json.loads(queries_path.read_text(encoding="utf-8"))
    section_key = f"{args.check}_check"
    if section_key not in queries_data:
        sys.exit(f"ERROR: section '{section_key}' not in queries.json")

    queries = queries_data[section_key].get("queries", [])
    if not queries:
        sys.exit(f"ERROR: no queries in {section_key}")

    # Drop queries with unresolved placeholders
    valid_queries = []
    skipped = []
    for q in queries:
        if "<null:" in q:
            skipped.append(q)
        else:
            valid_queries.append(q)

    if skipped:
        print(f"WARN: skipping {len(skipped)} queries with unresolved placeholders:", file=sys.stderr)
        for s in skipped:
            print(f"  - {s}", file=sys.stderr)

    api_key = load_api_key()
    client = TavilyClient(api_key)

    out = {
        "candidate": queries_data.get("candidate"),
        "archetype": queries_data.get("archetype"),
        "check": args.check,
        "timestamp": datetime.utcnow().isoformat() + "Z",
        "max_results": args.max_results,
        "retrieval_window": [start_date, end_date],
        "queries_executed": len(valid_queries),
        "queries_skipped": skipped,
        "results": [],
    }

    print(f"Tavily retrieval window: [{start_date}, {end_date}] (v1.5 time-bounded)")

    for i, q in enumerate(valid_queries, 1):
        print(f"  [{i}/{len(valid_queries)}] {q[:80]}...")
        try:
            r = client.search(
                q,
                max_results=args.max_results,
                start_date=start_date,
                end_date=end_date,
            )
            results = r.get("results", [])
            out["results"].append(
                {
                    "query": q,
                    "results": [
                        {
                            "title": item.get("title", ""),
                            "url": item.get("url", ""),
                            "content": (item.get("content", "") or "").strip()[:1200],
                            "published_date": item.get("published_date") or item.get("publishedDate"),
                        }
                        for item in results
                    ],
                }
            )
        except Exception as e:
            out["results"].append({"query": q, "error": str(e)})
            print(f"    Error: {e}", file=sys.stderr)
        time.sleep(args.sleep)

    out_path = working_dir / f"tavily_{args.check}_results.json"
    out_path.write_text(json.dumps(out, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"\nOK: wrote {out_path} ({len(valid_queries)} queries, {len(skipped)} skipped)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
